### ISSUE TITLE
how to apply this lat_lon_parser on pandas dataframe specific column?

### ISSUE THREAD

**Issue by ganbaaelmer** [NOAA-ORR-ERD/lat_lon_parser#11]
**how to apply this lat_lon_parser on pandas dataframe specific column?**

`df['Coordinates'] = df['Coordinates'].apply(parse(????))`

**Comment by ChrisBarker-NOAA** [comment]
I'm not all that familiar with pandas -- but tried this out -- you were SO close!

```
from lat_lon_parser import parse
df['Coordinates'] = df['Coordinates'].apply(parse)
```
pandas' `apply` method takes the function object itself -- so just parse, and it will call it on each of the elements in the series. At least that works for me:

```
In [20]: df = pandas.DataFrame({'coords':["12d13'N","32 5 14", "30.123W"]})

In [21]: df
Out[21]: 
    coords
0  12d13'N
1  32 5 14
2  30.123W

In [22]: df['coords'] = df['coords'].apply(parse)

In [23]: df
Out[23]: 
      coords
0  12.216667
1  32.087222
2 -30.123000
```

Thanks for the example, I've added it to the readme :-)
