### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by eumiro** [NOAA-ORR-ERD/lat_lon_parser#5]
This project needs a license. Choose one and add it to `setup.py`, so it gets released on PyPI and the license badge in `README.rst` gets updated automatically.

**Comment by ChrisBarker-NOAA** [comment]
Done: though apparently gitHub can't figure out CC0, Even though I used their template.  :-(

Thanks for moving this forward, I took the opportunity to update a bunch of the code, too.
