### ISSUE TITLE
Parsing of a tuple triggers Bad Operand Type

### ISSUE THREAD

**Issue by w103ejsNikon** [NOAA-ORR-ERD/lat_lon_parser#8]
Using Python 3.6.13, the following error was experienced. 

Example:
_lat = (39.0, 8.7711, 0.0)
_lat  = to_dec_deg(_lat)
*** TypeError: bad operand type for abs(): 'tuple'

However, passing the value into the function, not as a variable, returns the conversion.
to_dec_deg(39.0, 8.7711, 0.0), returns 39.146185

**Comment by ChrisBarker-NOAA** [comment]
This is how Python works:

The `to_dec_deg()` function takes three arguments.

```
def to_dec_deg(d=0, m=0, s=0, max=180):
    """
    DecDegrees = to_dec_deg(d=0, m=0, s=0)
    converts degrees, minutes, seconds to decimal degrees
    (returned as a float).
    """
```

In your example, when you call:

`_lat = to_dec_deg(_lat)` you are passing a single argument, which happens to be a tuple, so you get the error.

If you want to "unpack" the tuple into three argments, you can use the `*` operator:

`_lat = to_dec_deg(*_lat)`

should work.

**Comment by ChrisBarker-NOAA** [comment]
Closing as a not-a-bug.
